title: Cankun Guo Homepage
page-top-title: Cankun Guo Homepage
top-section-bg-text: A Passionate Multimodal Learning & AI Infra Enthusiast Aspiring to Build a Smarter AI Future
home-subtitle: Cankun Guo
copyright-text: '&copy; Cankun Guo 2024. All Rights Reserved. Template by Cankun Guo From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
